Update German translation v2.27.0
ruester/git-po-de pull request #10
Opened 2020-05-24 14:00 UTC by ruester

2020-05-25 07:26 UTC, ralfth requested changes
Nur ein kleiner Schreibfehler. Danke für deine Übersetzungen!

Reviewed-by: Ralf Thielow <ralf.thielow@gmail.com>

2020-05-25 07:26 UTC, ralfth commented on po/de.po
> +"indem Sie einen dr folgenden Befehle ausführen, bevor der nächste Pull\n"
dr -> der

2020-05-29 14:36 UTC, ruester commented on po/de.po
> +"indem Sie einen dr folgenden Befehle ausführen, bevor der nächste Pull\n"
Danke :smiley:

2020-05-29 14:41 UTC, ruester commented
Eine weitere Übersetzung kam jetzt noch vom rc-2 hinzu...

2020-05-29 14:43 UTC, ralfth approved these changes

2020-05-29 14:51 UTC, ruester commented
https://github.com/git-l10n/git-po/pull/455

2020-05-29 14:51 UTC, closed without merging

2020-05-29 14:56 UTC, ruester commented
Vielen Dank für dein Review, @ralfth! Ich hatte den Review diesmal ohne eine Ankündigung über die Google-Mailing-Gruppe angekündigt und nur GitHub genutzt. Ich hoffe, das ihr beide dadurch automatisch eine Mail bekommen habt und wir weiterhin die Review-Funktionalität von GitHub nutzen können, ohne über Mailing-Gruppen kommunizieren zu müssen :wink: :+1: