Update German translation for Git 2.28.0
ruester/git-po-de pull request #12
Opened 2020-07-21 15:16 UTC by ruester

2020-07-21 15:19 UTC, ruester commented
As always, only the changes of https://github.com/ruester/git-po-de/pull/12/commits/6464f3174616c3716d1333044902a053c545ef7f needs be reviewed, as the other commit is the automatic update of the .po file :wink: :+1:

2020-07-22 16:04 UTC, ralfth requested changes
Danke für deine Übersetzungen!

2020-07-22 16:04 UTC, ralfth commented on po/de.po
> +msgstr "Ergänzung vom Index und Arbeitsverzeichnis verwerfen [y,n,q,a,d%s,?]? "
... im Index und ...

2020-07-22 16:04 UTC, ralfth commented on po/de.po
> +msgstr "Sammeln referenzierter Commits"
Sammle referenzierte Commits ?

2020-07-22 16:04 UTC, ralfth commented on po/de.po
> +msgstr "Server unterstützt das Objekt-Format dieses Repositorys nicht"
Repositories

2020-07-22 16:04 UTC, ralfth commented on po/de.po
> +msgstr "der Server unterstützt den Algorithmus '%s' nicht"
Ich würde 'den' weglassen.

2020-07-22 16:04 UTC, ralfth commented on po/de.po
> +msgstr "fehlerhaftes Objekt-Format bei '%s'"
nicht unterstütztes ...

2020-07-22 16:04 UTC, ralfth commented on po/de.po
> +msgstr "Sammeln der Commits von der Standard-Eingabe"
Sammle Commits von der Standard-Eingabe ?

2020-07-22 16:04 UTC, ralfth commented on po/de.po
> +msgstr "leite nach %s um"
Umleitung nach %s ?

2020-07-22 16:04 UTC, ralfth commented on po/de.po
> -#~ msgstr "Ziel '%s' existiert bereits."
Diese Zeilen sollten dann noch entfernt werden.

2020-07-22 16:46 UTC, ruester commented on po/de.po
> -#~ msgstr "Ziel '%s' existiert bereits."
Sind sie ja schon 👍

2020-07-22 16:49 UTC, ralfth commented on po/de.po
> -#~ msgstr "Ziel '%s' existiert bereits."
Oh man. Ich hab offenbar 'ne rot/grün und +/- Schwäche. ;-)

2020-07-22 16:53 UTC, ruester commented on po/de.po
> +msgstr "Ergänzung vom Index und Arbeitsverzeichnis verwerfen [y,n,q,a,d%s,?]? "
Das ist besser, danke!

2020-07-22 16:53 UTC, ruester commented on po/de.po
> +msgstr "Sammeln referenzierter Commits"
Danke! 👍

2020-07-22 16:54 UTC, ruester commented on po/de.po
> +msgstr "Server unterstützt das Objekt-Format dieses Repositorys nicht"
Besser! 👍

2020-07-22 16:55 UTC, ruester commented on po/de.po
> +msgstr "der Server unterstützt den Algorithmus '%s' nicht"
👍

2020-07-22 16:56 UTC, ruester commented on po/de.po
> +msgstr "fehlerhaftes Objekt-Format bei '%s'"
ohje.. ja, das war falsch, danke!

2020-07-22 16:57 UTC, ruester commented on po/de.po
> +msgstr "Sammeln der Commits von der Standard-Eingabe"
Ja, das ist besser! 👍

2020-07-22 16:58 UTC, ruester commented on po/de.po
> +msgstr "leite nach %s um"
Vielen Dank, klingt besser! 👍

2020-07-22 17:01 UTC, ruester commented
Vielen Dank für dein Review, @ralfth! 😃 
Habe ich alles so übernommen 👍

2020-07-23 05:07 UTC, ralfth approved these changes
Danke!

Reviewed-by: Ralf Thielow <ralf.thielow@gmail.com>

2020-07-24 18:39 UTC, ruester commented
https://github.com/git-l10n/git-po/pull/465

2020-07-24 18:39 UTC, closed without merging