Update German translation for Git v2.31.0
ruester/git-po-de pull request #15
Opened 2021-03-03 19:23 UTC by ruester

@ralfth and @PhillipSz: please have a look at my suggestions for the German translation of Git v2.31.0. Only the commit b5e9ed2611 needs to be reviewed, the first commit is the automatically generated one to update the po file.

As always I also cleaned up some other translations that were not related to the current update. Some of these changes are proposed as best practises by the software poedit (which is also used by other translation teams).

2021-03-04 19:26 UTC, PhillipSz requested changes
Hey Matthias,

vielen Dank für deine Arbeit! Habe ein paar Kommentare hinzugefügt. Aber sieht bis auf zwei Typos sehr gut aus.

Viele Grüße
Phillip

(Habe die Kommentare erst im Commit und nicht im Review gemacht, falls dir das angezeigt wird nicht wundern. Habe es aber korrigiert)

2021-03-04 19:26 UTC, PhillipSz commented on po/de.po
> +msgstr "Fehler beim Codieren von '%s' von %s nach %s"
Weißt durch was die "%s" ersetzt werden? Weil davon abhängig könnte das zweite "von" auch ein "aus" sein. Könnte auch Sinn ergeben.

2021-03-04 19:26 UTC, PhillipSz commented on po/de.po
> +msgstr "Codierung '%s' von %s nach %s und zurück ist nicht dasselbe"
hier stellt sich dann die gleiche Frage.

2021-03-04 19:26 UTC, PhillipSz commented on po/de.po
> +msgstr "kann nicht chmod %cx '%s'"
Glaube im Deutschen fände ich ein "ausführen" am Ende nicht schlecht.

2021-03-04 19:26 UTC, PhillipSz commented on po/de.po
> +"keine Objektnkeine Objektnamen für Grenz-Commits anzeigen (Standard: aus)"
"keine Objektnamen für Grenz-Commits anzeigen (Standard: aus)"

2021-03-04 19:26 UTC, PhillipSz commented on po/de.po
> +"--depth wird in lokalen Klonen ignoriert; benutzen Sie stattdessen file://"
Im englischen ist ein Punkt am Ende. Vielleicht file:// in Anführungszeichen, damit es klar ist das der nicht dazugehört?

2021-03-04 19:26 UTC, PhillipSz commented on po/de.po
> +msgstr " Erweitern des Pfades '%s'"
Überflüssiger Leerschritt am Anfang

2021-03-04 19:26 UTC, PhillipSz commented on po/de.po
> +msgstr "alle Submodule autragen"
Da fehlt das "s" bei "autragen"

2021-03-05 04:58 UTC, ralfth commented on po/de.po
> +msgstr "Fehler beim Codieren von '%s' von %s nach %s"
Das erste %s ist ein Pfad, die beiden weiteren Zeichencodierungen.

2021-03-05 05:29 UTC, ralfth requested changes
Danke für deine Übersetzung!

2021-03-05 05:29 UTC, ralfth commented on po/de.po
> +msgstr "überspringe die Ausgabe zum angegebenen Pfad"
... bis zum angegebenen Pfad
?

2021-03-05 05:29 UTC, ralfth commented on po/de.po
> +msgstr " Erweitern des Pfades '%s'"
Fehler beim Erweitern des Pfades '%s'

2021-03-05 05:29 UTC, ralfth commented on po/de.po
> +"<git@vger.kernel.org> senden.  Danke.\n"
Nur ein Leerzeichen vor "Danke". Im Englischen werden häufig zwei Leerzeichen verwendet, aber im Deutschen gibt's das nicht.

2021-03-05 05:29 UTC, ralfth commented on po/de.po
> +"Umbenennung\n"
Nur ein Leerzeichen.

2021-03-06 15:31 UTC, ruester commented on po/de.po
> +msgstr "Fehler beim Codieren von '%s' von %s nach %s"
Dann würde ich das erstmal so lassen, ok?

2021-03-06 15:32 UTC, ruester commented on po/de.po
> +msgstr "Codierung '%s' von %s nach %s und zurück ist nicht dasselbe"
Dann "Codierung von ...", wie bei der Übersetzung davor :+1:

2021-03-06 15:39 UTC, ruester commented on po/de.po
> +"<git@vger.kernel.org> senden.  Danke.\n"
Vielen Dank! Das wusste ich noch gar nicht :+1:

2021-03-06 15:42 UTC, ruester commented
Vielen Dank für euer Review! Die Vorschläge habe ich soweit von euch übernommen :+1:

2021-03-06 15:55 UTC, ralfth commented
Danke!
Reviewed-by: Ralf Thielow <ralf.thielow@gmail.com>

2021-03-06 16:30 UTC, ruester commented
There was another translation round, please have a look again at the new translations in commit e7499f7b92. <br>
The other commits were not changed and only rebased onto the new git-po master branch.

2021-03-06 16:30 UTC, ralfth approved these changes

2021-03-07 19:51 UTC, PhillipSz approved these changes

2021-03-07 19:54 UTC, PhillipSz commented
Top, danke!

Danke! Reviewed-by: Phillip Szelat phillip.szelat@gmail.com

2021-03-08 18:53 UTC, ruester commented
Vielen Dank für eure Hilfe! 😃 
https://github.com/git-l10n/git-po/pull/511

2021-03-08 18:55 UTC, closed without merging