Review: Update German translation for Git v2.34.0
ruester/git-po-de pull request #17
Opened 2021-11-07 19:22 UTC by ruester

@ralfth and @PhillipSz: please have a look at my suggestions for the German translation of Git v2.34.0. Only the commit 88bddee759 needs to be reviewed, the first commit is the automatically generated one to update the po file.

2021-11-08 15:22 UTC, PhillipSz requested changes
Hallo Matthias,

vielen Dank für deine Übersetzungen. Habe nur eine Sache gefunden, sonst passt alles!

Viele Grüße
Phllip

2021-11-08 15:22 UTC, PhillipSz commented on po/de.po
> +msgstr "git bisect--helper --bisect-run <Programm>"
würde das "…" behalten

2021-11-08 17:24 UTC, ralfth requested changes
Danke für die Übersetzungen! Gute Arbeit! Nur ein paar kleine Anmerkungen.

2021-11-08 17:24 UTC, ralfth commented on po/de.po
> +msgstr "user.signingkey muss für die SSH-Signatur festgelegt werden"
... gesetzt sein
?

2021-11-08 17:24 UTC, ralfth commented on po/de.po
> +msgstr "Führen Sie stattdessen '%s' aus? (y/N)"
Stattdessen '%s' ausführen? (y/N)

2021-11-08 17:24 UTC, ralfth commented on po/de.po
> +msgstr "Zeile konnte nicht analysiert werden: %s"
...geparst werden...
Das verwenden wir schon an anderen Stellen.

2021-11-08 17:24 UTC, ralfth commented on po/de.po
> +msgstr "schreibe nur Multipack-Bitmap-Index, die vorgegebene Indexe enthalten"
Multipack-Index schreiben, der nur die gegebenen Indexe enthält

2021-11-08 17:24 UTC, ralfth commented on po/de.po
> +msgstr "Merge von '%s' in Submodul-Pfad '%s' fehlgeschlagen"
... nicht möglich

Wäre dann dieselbe Übersetzung wie oben.

2021-11-08 17:24 UTC, ralfth commented on po/de.po
> +msgstr "'%s' ist bereits zum Commit vorgemerkt"
Ich denke,
'%s' existiert bereits im Index
ist hier besser.

Das war wohl schon vorher falsch.

2021-11-08 17:24 UTC, ralfth commented on po/de.po
> +msgstr "'%s' ist bereits zum Commit vorgemerkt und ist kein Submodul"
dito
... existiert bereits im Index...

2021-11-12 15:28 UTC, ruester commented on po/de.po
> +msgstr "git bisect--helper --bisect-run <Programm>"
Vielen Dank! :smiley:

2021-11-12 15:35 UTC, ruester commented on po/de.po
> +msgstr "user.signingkey muss für die SSH-Signatur festgelegt werden"
ja, besser, danke :smiley:

2021-11-12 15:36 UTC, ruester commented on po/de.po
> +msgstr "Führen Sie stattdessen '%s' aus? (y/N)"
ja, viel besser :+1:

2021-11-12 15:38 UTC, ruester commented on po/de.po
> +msgstr "schreibe nur Multipack-Bitmap-Index, die vorgegebene Indexe enthalten"
ohje :see_no_evil:  danke!

2021-11-12 15:44 UTC, ruester commented
Vielen Dank für euer Review, @PhillipSz und @ralfth !
Habe ich alles so übernommen :wink: :+1: 
Schicke ich dann jetzt als Pull Request zum Maintainer...

2021-11-12 15:51 UTC, ruester commented
I had to fix one more message, see 6b3208aeb2fe35c0a8332ee7039bfb329a5e7edf
Also one new message was added in translation round #3, see f36265d1e9e675ef85a880eedb377a9a7b254f8e

2021-11-12 16:06 UTC, ruester commented
https://github.com/git-l10n/git-po/pull/594

2021-11-12 16:06 UTC, closed without merging