Review: Update German translation for Git v2.35.0
ruester/git-po-de pull request #19
Opened 2022-01-15 18:15 UTC by ruester

@ralfth and @PhillipSz: Please have a look at my suggestions for the German translation of Git v2.35.0. Only the commits b63e8aaa6c (fix from @jottkaerr) and d99fa3c4fb needs to be reviewed, the commit 4ab1b1ff6a is the automatically generated one to update the po file.
As always I also updated some other translations that are not part of this Git update. For example omitting the full stop at the end of a sentence if the original string does not contain one or starting with a small letter after a semicolon...

2022-01-15 19:08 UTC, ralfth requested changes
Thank you for the translation! Please have a look at my suggestions for improvement.

2022-01-15 19:08 UTC, ralfth commented on po/de.po
> +"kann Aktualisierung des Branch '%s' nicht erzwingen, ausgecheckt in '%s'"
... des Branches ...

2022-01-15 19:08 UTC, ralfth commented on po/de.po
> +msgstr "Stattdessen '%s' ausführen? (y/N) "
(y/N) should be inside the sentence. Like " ... (y/N)? "

2022-01-15 19:08 UTC, ralfth commented on po/de.po
> +msgstr "Leeren Commit erzeugen: %.*s"
"Erzeuge leeren Commit: %.*s"

2022-01-15 19:08 UTC, ralfth commented on po/de.po
> +msgstr "Anfordern der Branch '%s' verweigert, ausgecheckt in '%s'"
"Anfordern in Branch '%s' ..."

2022-01-15 19:08 UTC, ralfth commented on po/de.po
> +msgstr "<Name> statt echter Ziel-Branch verwenden"
<Name> statt echten Ziel-Branch verwenden

2022-01-15 19:08 UTC, ralfth commented on po/de.po
> +"existierenden Muster des partiellen Checkouts benutzen nicht den Cone-Modus"
"existierende Muster..."

2022-01-15 19:08 UTC, ralfth commented on po/de.po
> +msgstr "nur Änderungen in den Stash, die zum Commit vorgemerkt wurden"
maybe 'nur Änderungen stashen, die zum Commit vorgemerkt sind'?

2022-01-15 19:08 UTC, ralfth commented on po/de.po
> +"Nutzung von \"absorbgitdirs\" wird dieses durch eine .git-Datei ersetzt."
"die Nutzung ..." ?

2022-01-15 19:08 UTC, ralfth commented on po/de.po
> +msgstr "lade nur Metadaten des Branch herunter, der ausgecheckt wird"
"... des Branches ..."

2022-01-15 19:08 UTC, ralfth commented on po/de.po
> +msgstr "Fehler beim Abfragen des Default-Branch für '%s'"
"... Default-Branches ..."

2022-01-15 19:08 UTC, ralfth commented on po/de.po
> +msgstr "ungültige Git-Version"
"Git-Version einbeziehen"

2022-01-20 17:01 UTC, ruester commented on po/de.po
> +"kann Aktualisierung des Branch '%s' nicht erzwingen, ausgecheckt in '%s'"
thanks! I also fixed the same mistake for the translation in `contrib/scalar/scalar.c:380`

2022-01-20 17:05 UTC, PhillipSz commented
Hey, danke für die Übersetzung! Habe gerade keine Zeit für den Review. Aber ich denke @ralfth hat das schon gut gemacht.

Viele Grüße 
Phillip

2022-01-20 17:06 UTC, ruester commented on po/de.po
> +msgstr "ungültige Git-Version"
🙈 thanks!

2022-01-20 17:12 UTC, ruester commented
@ralfth Thanks for your review, I applied all your changes 👍

2022-01-20 17:16 UTC, ruester commented
There was an update in the upstream repository so I had to rebase to master again and update the de.po

2022-01-20 17:20 UTC, ralfth commented
Looks good to me. Thanks!
Reviewed-by: Ralf Thielow <ralf.thielow@gmail.com>

2022-01-20 17:28 UTC, ruester commented
https://github.com/git-l10n/git-po/pull/608

2022-01-20 17:28 UTC, closed without merging