Review: Update German translation for Git v2.37
ruester/git-po-de pull request #21
Opened 2022-06-20 19:04 UTC by ruester

@ralfth and @PhillipSz: Please have a look at my suggestions for the German translation of Git v2.37. Only the commit b3075795cf needs to be reviewed, the commit 80891eb836 is the automatically generated one to update the po file.
There was also a change for the location metadata of the po files, they should now be "location-less" to reduce noise and size of the Git repository, see the po/README.md for more details. The commit for removing the location lines is 86c5b80372.

2022-06-21 13:32 UTC, ralfth requested changes
Very good translation. Thank you!

Just found 2 small things that can be improved.

2022-06-21 13:32 UTC, ralfth commented on po/de.po
> +"Oder gehe auf Version v2.33, oder früher, zurück, um den Rebase "
Maybe we want to replace the last space with \n.

2022-06-21 13:32 UTC, ralfth commented on po/de.po
> +msgstr "BHFI has sich verändert '%ls'"
I think this should read "BHFI hat '%ls' verändert".

2022-06-21 18:20 UTC, ruester commented on po/de.po
> +msgstr "BHFI has sich verändert '%ls'"
yes, thanks! :see_no_evil:

2022-06-21 18:32 UTC, ruester commented
I also added the commit for changing the team leader. @PhillipSz I've discussed this with Ralf and now I also want to inform you that I will retire the team lead for the German translations. But I will stay with you as a reviewer :wink:

2022-06-22 05:38 UTC, ralfth approved these changes
Looks good to me. Thank you!

Reviewed-by: Ralf Thielow <ralf.thielow@gmail.com>

2022-06-22 17:15 UTC, ruester commented
https://github.com/git-l10n/git-po/pull/642

2022-06-22 17:15 UTC, closed without merging