Update German translation v2.23.0
ruester/git-po-de pull request #4
Opened 2019-08-10 12:20 UTC by ruester

2019-08-10 16:56 UTC, PhillipSz reviewed
Hey,

habe mal zwei/drei Dinge angemerkt die mir aufgefallen sind.

Habe gerade nochmal nach geschaut und wir haben bisher immer "der Branch" gesagt und würde das auch beibehalten :)

Vielen Dank für deine Arbeit!

2019-08-10 16:56 UTC, PhillipSz commented on po/de.po
> +"ohne Auswirkungen auf irgendeinen Branch verwerfen, indem Sie zu einer\n"
hmm nach meinem Sprachgefühl ist es "der Branch" und wäre dann entsprechend "zu einem anderen Branch"

2019-08-10 16:56 UTC, PhillipSz commented on po/de.po
> +msgstr "Um ein Paket zu verifizieren wird ein Repository benötigt."
vielleicht überprüfen statt verifizieren? Bin mir aber auch nicht sicher, was denkst du?

2019-08-10 16:56 UTC, PhillipSz commented on po/de.po
> +msgstr "Interaktiver Modus benötigt Patch-Dateien in der Kommandozeile"
Würde auf der Kommandozeile sagen oder bei der Nutzung der Kommandozeile

2019-08-10 16:56 UTC, PhillipSz commented on po/de.po
> +msgstr "Sie wechseln die Branch während einer binären Suche"
"den"

2019-08-10 16:56 UTC, PhillipSz commented on po/de.po
> +msgstr "jedes geklonte Submodul nutzt seine Remote-Tracking-Branch"
seinen

2019-08-10 16:58 UTC, PhillipSz reviewed
Passt alles, habe nur eine Anmerkung hinzugefügt

2019-08-10 16:58 UTC, PhillipSz commented on po/de.po
> +"hatten, aber diese Überprüfung wurde deaktiviert. Um es wieder zu\n"
Würde vielleicht "Um diese wieder zu aktivieren" sagen.

2019-08-10 17:05 UTC, ralfth requested changes
Danke für die Übersetzung!
In meinem Review sind viele Wiederholungen dabei, also eigentlich weniger als es aussieht.

2019-08-10 17:05 UTC, ralfth commented on po/de.po
> +"anderen Branch wechseln.\n"
... zu einem
anderen Branch zurückwechseln.

2019-08-10 17:05 UTC, ralfth commented on po/de.po
> +msgstr "Ungültiges filter-spec '%s'"
"Ungültige" (ohne s)?!

2019-08-10 17:05 UTC, ralfth commented on po/de.po
> +msgstr "versuchen Sie \"git revert (--continue | %s--abort | --quit)\""
Versuchen Sie...?

2019-08-10 17:05 UTC, ralfth commented on po/de.po
> +msgstr "\"cherry-pick\" ist bereits im Gange"
"cherry-pick" wird bereits durchgeführt

Ich weiß, "bereits im Gange" wird häufig verwendet, aber "wird bereits durchgeführt" klingt besser.

2019-08-10 17:05 UTC, ralfth commented on po/de.po
> +msgstr "versuchen Sie \"git cherry-pick (--continue | %s--abort | --quit)\""
Versuchen ...

2019-08-10 17:05 UTC, ralfth commented on po/de.po
> +"Wurde bereits committet?\n"
"Haben Sie bereits committet?"

2019-08-10 17:05 UTC, ralfth commented on po/de.po
> +msgstr[0] "%u Bytes"
"Byte" wie in "1 Byte"

2019-08-10 17:05 UTC, ralfth commented on po/de.po
> +msgstr[0] "%u Bytes/s"
Byte/s wie in "1 Byte/s"

2019-08-10 17:05 UTC, ralfth commented on po/de.po
> +"Es wurden %.2f Sekunden benötigt, um die voraus/hinterher-Werte der Branch\n"
"der Branch" entfernen

2019-08-10 17:05 UTC, ralfth commented on po/de.po
> +msgstr "Interaktiver Modus benötigt Patch-Dateien in der Kommandozeile"
Vielleicht "Patches"?

2019-08-10 17:05 UTC, ralfth commented on po/de.po
> +msgstr "Eine Branch wird erwartet, Tag '%s' bekommen"
Ein Branch ...

2019-08-10 17:05 UTC, ralfth commented on po/de.po
> +msgstr "Eine Branch wird erwartet, Remote-Branch '%s' bekommen"
Ein Branch ...

2019-08-10 17:05 UTC, ralfth commented on po/de.po
> +msgstr "Eine Branch wird erwartet, '%s' bekommen"
Ein Branch ...

2019-08-10 17:05 UTC, ralfth commented on po/de.po
> +msgstr "Eine Branch wird erwartet, Commit '%s' bekommen"
Ein Branch ...

2019-08-10 17:05 UTC, ralfth commented on po/de.po
> +"Die Branch kann nicht während eines Merges gewechselt werden.\n"
Der Branch ...

2019-08-10 17:05 UTC, ralfth commented on po/de.po
> +"Die Branch kann nicht während eines laufenden 'am'-Befehls gewechselt "
Der Branch ...

2019-08-10 17:05 UTC, ralfth commented on po/de.po
> +"Die Branch kann nicht während eines laufenden 'revert'-Befehls gewechselt "
Der Branch ...

2019-08-10 17:05 UTC, ralfth commented on po/de.po
> +"Die Branch kann nicht während eines laufenden 'cherry-pick'-Befehls "
Der ...

2019-08-10 17:05 UTC, ralfth commented on po/de.po
> +"Die Branch kann nicht während eines laufenden 'revert'-Befehls gewechselt "
Der ...

2019-08-10 17:05 UTC, ralfth commented on po/de.po
> +msgstr "Sie wechseln die Branch während einer binären Suche"
... den Branch ...

2019-08-10 17:05 UTC, ralfth commented on po/de.po
> +msgstr "Sie müssen ein Pfad zum Wiederherstellen angeben."
"Sie müssen Pfad(e) zur Wiederherstellung angeben."

2019-08-10 17:05 UTC, ralfth commented on po/de.po
> +msgstr "kein zweites Erraten bei 'git checkout <kein-solcher-Branch>' "
"zweite Vermutung 'git checkout <kein-solcher-Branch' (Standard)"
Vielleicht auch mit großen "z" beginnend?

2019-08-10 17:05 UTC, ralfth commented on po/de.po
> +msgstr "kein zweites Erraten bei 'git switch <kein-solcher-Branch>'"
"zweite Vermutung" ... s.o.

2019-08-10 17:05 UTC, ralfth commented on po/de.po
> +msgstr "jedes geklonte Submodul nutzt seine Remote-Tracking-Branch"
... seinen ...

2019-08-10 17:05 UTC, ralfth commented on po/de.po
> +"[--reachable|--stdin-packs|--stdin-commits] <Split Optionen>"
Vielleicht "Split-Optionen"?!

2019-08-10 17:05 UTC, ralfth commented on po/de.po
> +msgstr "git env--helper --type=[bool|ulong] <Optionen> <Umgebungsvariablen>"
Umgebungsvariable

2019-08-10 17:05 UTC, ralfth commented on po/de.po
> +msgstr "Standard für git_env_*(...) um darauf zurückzugreifen"
", um darauf"

2019-08-10 17:05 UTC, ralfth commented on po/de.po
> +msgstr "Auswählen der Behandlung von Commit-Beschreibungen in wechselndem "
... bei wechselndem ...

2019-08-10 17:05 UTC, ralfth commented on po/de.po
> +msgstr "Prüfe auf erzwungene Aktualisierungen in allen aktualisieren Branches"
... aktualisierten ...

2019-08-10 17:05 UTC, ralfth commented on po/de.po
> +"Es brauchte %.2f Sekunden, um auf erzwungene Aktualisierungen zu prüfen. "
... um erzwungene Aktualisierungen zu überprüfen.

2019-08-10 17:05 UTC, ralfth commented on po/de.po
> +msgstr "--abort, aber Index und Arbeitsverzeichnis bleibt unverändert"
... unverändert lassen

2019-08-10 17:17 UTC, ralfth requested changes
Danke für die Übersetzung!

2019-08-10 17:17 UTC, ralfth commented on po/de.po
> +"Normalerweise zeigt 'fetch' welche Branches eine erzwungene Aktualisierung\n"
", welche"

2019-08-10 17:38 UTC, ralfth commented on po/de.po
> +msgstr "Interaktiver Modus benötigt Patch-Dateien in der Kommandozeile"
oder "über die Kommandozeile"

2019-08-10 18:02 UTC, ruester commented on po/de.po
> +msgstr[0] "%u Bytes"
Hatte ich auch zuerst so überlegt.. nur die vorherige Version hatte halt auch "Bytes", neu hinzugekommen ist ja "%u"
Werde jetzt also "Byte" nehmen ;-)

2019-08-10 18:18 UTC, ruester commented on po/de.po
> +"Normalerweise zeigt 'fetch' welche Branches eine erzwungene Aktualisierung\n"
Sehe ich nicht so.. "Normalerweise zeigt 'fetch'" ist kein ganzer Satz. Und mit "welche" wird 'fetch' auch nicht näher beschrieben (wenn es ein Nebensatz wäre).

2019-08-10 18:31 UTC, ruester commented
Vielen Dank für eure Reviews! Das hat sehr geholfen und ich konnte alles von euch so übernehmen. Zu "der Branch" werde ich mir jetzt als Analogie "der Abzweig/Zweig/Ast" merken, damit das nächstes mal besser klappt ;-)
Für mich war es immer "die Abzweigung", weshalb für mich wohl "die Branch" geläufig war...
Habe auch gleich mal meine Wiki-Seite dazu angepasst:
https://github.com/ruester/git-po-de/wiki/Translation-Guidelines

Habe jetzt einen weiteren Commit mit euren Änderungen hinzugefügt, wenn alles so o.k. ist, dann bitte mit einem kurzen
```
Reviewed-by Name <mail@address>
```
hier als Kommentar bestätigen, dann füge ich das im Commit hinzu ;-)

2019-08-10 19:00 UTC, ralfth commented on po/de.po
> +"Normalerweise zeigt 'fetch' welche Branches eine erzwungene Aktualisierung\n"
OK

2019-08-10 19:03 UTC, ralfth approved these changes

2019-08-10 19:05 UTC, ralfth commented
Reviewed-by: Ralf Thielow <ralf.thielow@gmail.com>

Danke!

2019-08-12 16:51 UTC, PhillipSz approved these changes
Reviewed-by: Phillip Szelat <phillip.szelat@gmail.com>

2019-08-12 16:56 UTC, ruester commented
Squashed into master and opened PR at https://github.com/git-l10n/git-po/pull/390
Thanks again!

2019-08-12 16:56 UTC, closed without merging