Update German translation v2.25.0
ruester/git-po-de pull request #7
Opened 2020-01-05 19:08 UTC by ruester

2020-01-09 10:05 UTC, ralfth requested changes
Danke für die sehr gute Übersetzung!

Reviewed-by: Ralf Thielow <ralf.thielow@gmail.com>

2020-01-09 10:05 UTC, ralfth commented on po/de.po
> +msgstr "Angegebene Elementen abwählen"
... Elemente ... (ohne n)

2020-01-09 14:20 UTC, PhillipSz approved these changes
Alles super! Vielen Dank!

Reviewed-by: Phillip Szelat phillip.szelat@gmail.com

2020-01-09 17:10 UTC, ruester commented
Vielen Dank für eure Reviews! 😃 
Den einen Fehler ändere ich noch, danke Ralf! 👍
Ich war mir nur etwas unsicher bei "hunk". Bei de Erklärungen zum interaktiven "git add", fand ich "Block" besser, aber "Patch-Block" wäre ja auch möglich und ausführlicher (https://github.com/ruester/git-po-de/wiki/Translation-Guidelines)...

2020-01-10 10:57 UTC, ruester commented on po/de.po
> +msgstr "Angegebene Elementen abwählen"
Fixed, danke!

2020-01-10 11:10 UTC, ruester commented
https://github.com/git-l10n/git-po/pull/413

2020-01-10 11:10 UTC, closed without merging